name: deploy website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - uses: amondnet/vercel-action@v20
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: ${{ secrets.ORG_ID }}
          vercelProjectId: ${{ secrets.PROJECT_ID }}
          githubToken: ${{ secrets.PAT }}
          sourceDirectory: "src"
        env:
          YOUR_ENV_1: ${{ secrets.YOUR_ENV_1 }}
          YOUR_ENV_2: ${{ secrets.YOUR_ENV_2 }}